import type { Metadata } from "next";
import { Raleway } from "next/font/google";
import Header from "./components/Header";
import "./globals.css";

const raleway = Raleway({ subsets: ["latin"], weight: ["400", "600", "700"] });

export const metadata: Metadata = {
  icons: {
    icon: "/assets/images/logo.png",
  },
  title: "FOSO",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${raleway.className}`}>
        <Header />
        <main className="pt-[100px] px-10">{children}</main>
      </body>
    </html>
  );
}
